### ISSUE TITLE
Is it really a burrito?

### ISSUE THREAD

**Issue by tjlytle** [phoneburner/http-tortilla#2]
@michaelnetworx makes a good case that this is really a tortilla, and @andysnell mentions that the concept is good for any wrapper. So two options for naming:
- `http-burrito`
- `http-tortilla`

Or just keep it the same. Use the comments below for voting, and the thread to weigh in.

**Comment by tjlytle** [comment]
`http-burrito`

**Comment by tjlytle** [comment]
`http-tortilla`

**Comment by tjlytle** [comment]
`burrito`

**Comment by shanewiredin** [comment]
http sounds insecure

**Comment by mchamplain** [comment]
if we keep this lightweight, I vote for tortilla... if we add a bunch of features then I'll go with burrito 😄

**Comment by johncongdon** [comment]
Burrito is just more fun to say, and more tangible.

**Comment by networx** [comment]
Agree burrito more fun to say and there is an emoji.

**Comment by tjlytle** [comment]
> if we keep this lightweight, I vote for tortilla... if we add a bunch of features then I'll go with burrito

@mchamplain this should only ever be the traits needed for wrapping. If we publish our own internal request / response (that uses this), it'll be another package.

**Comment by tjlytle** [comment]
> Burrito is just more fun to say, and more tangible.

@johncongdon well, should we release the request / response code @josephlavin put together, _it_ could be `http-burrito` as it uses `http-tortilla`.

**Comment by jackdpeterson** [comment]
I vote for burrito. It will forever cause hostility about the inaccuracy of the metaphor and launch this library to git viral levels as a consequence. Reddit debates will be built on this.

**Comment by tjlytle** [comment]
@jackdpeterson makes some good points (but didn't actually vote).

**Comment by tjlytle** [comment]
Well, 2 days in we're at a 50 / 50 split (if we count @jackdpeterson's :rocket:):
![image](https://user-images.githubusercontent.com/125074/69341555-ca994b80-0c37-11ea-8736-0339806f8352.png)

So I'm torn on what to do:
![image](https://user-images.githubusercontent.com/125074/69341836-5317ec00-0c38-11ea-97a7-b783b829d9ec.png)

**Comment by tjlytle** [comment]
I'm casting my vote for tortilla, with hopes that we also open source our wrapped request with the much catchier `http-burrito`.
